apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: appdeploy
  namespace: test
  labels:
    app: flask
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appdeploy
  service:
    port: 5000
    gateways:
    - appdeploy-gateway
    hosts:
    - "*"
  analysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 3
    # max traffic percentage routed to canary percentage (0-100)
    maxWeight: 50
    # canary increment step percentage (0-100)
    stepWeight: 20
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      # maximum req duration P99
      thresholdRange:
        max: 500
      interval: 30s
    # testing (optional)
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.default/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 curl http://appdeploy-canary:5000/return_version"